name: Build browNet EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt6 qasync fastapi uvicorn aiohttp aiosqlite beautifulsoup4 lxml tldextract aiohttp_socks scikit-learn numpy joblib nltk language_tool_python

    - name: Build EXE
      run: |
        python -m PyInstaller --onefile --noconsole --clean --add-data "index.html;." --name "browNet" app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: logiciel-browNet
        path: dist/*.exe
