nom: Générer browNet EXE
sur: [pousser]

emplois:
  construire:
    continue sur: windows-latest
    mesures:
      - utilise: actions/checkout@v4
      - nom: Installer Python
        utilise: actions/setup-python@v5
        avec:
          version de Python: '3.10'

      - nom: Installer toutes les dépendances
        courir: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6 PyQt6-WebEngine qasync fastapi uvicorn aiohttp aiosqlite beautifulsoup4 lxml tldextract aiohttp_socks scikit-learn numpy joblib nltk language_tool_python aiofiles requests cachetools google-re2 python-magic

      - nom: Générer EXE
        courir: |
          python -m PyInstaller --onefile --noconsole --clean --add-data "index.html;." --name "browNet" app.py

      - nom: Télécharger l'artefact
        utilise: actions/upload-artifact@v4
        avec:
          name: logiciel-browNet
          path: dist/*.exe
